### ISSUE TITLE
enable usage of spring-jdbc version >= 4.2.x

### ISSUE THREAD

**Issue by lfischer** [zalando/java-sproc-wrapper#35]
Spring boot version 1.4 comes with dependencies to spring-jdbc version 4.3

Using it together with zalando-sprocwrapper results in this exception:

```
java.lang.ClassNotFoundException: org.springframework.jdbc.core.simple.ParameterizedRowMapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.zalando.typemapper.core.TypeMapperFactory.createTypeMapper(TypeMapperFactory.java:16)
	at de.zalando.sprocwrapper.proxy.executors.SingleRowTypeMapperExecutor.executeSProc(SingleRowTypeMapperExecutor.java:21)
	at de.zalando.sprocwrapper.proxy.StoredProcedure.execute(StoredProcedure.java:465)
	at de.zalando.sprocwrapper.proxy.SProcProxy.invoke(SProcProxy.java:48)
```
The class org.springframework.jdbc.core.simple.ParameterizedRowMapper is deprecated since 4.1 and was removed in 4.2
(http://docs.spring.io/spring/docs/4.1.x/javadoc-api/org/springframework/jdbc/core/simple/ParameterizedRowMapper.html)

**Comment by lfischer** [comment]
Looks like this was already fixed in 1.5.1. I only used the outdated version 1.4.0.

**Comment by JavaHelper** [comment]
@lfischer - What exact changes do I need to used in order to avoid this error?

**Comment by vadeg** [comment]
@JavaHelper version `2.0.0` was released last year. It uses spring 4.3.8. You can try to switch into new library version
